### ISSUE TITLE
I'm confused that ........

### ISSUE THREAD

**Issue by Pacio** [bolucat/naive#2] opened 2022-09-25 13:42 UTC
What confuses me very much is that the domain name that cannot be accessed after setting up the service after the complete installation guide and the proxy service fails, the most important thing is that /var/log/caddy does not generate any logs

**Comment by Pacio** [comment] 2022-09-25 13:44
I wonder if it's because I used a free ml domain name because I didn't find any certificate files in the folder

**Comment by Pacio** [comment] 2022-09-25 14:24
After referring to some other caddyfile configurations, I deleted

servers :443 {
     protocols h1 h2 h3
  }
and now it works

**Comment by bolucat** [comment] 2022-09-25 15:53
> I wonder if it's because I used a free ml domain name because I didn't find any certificate files in the folder

Sorry but, I didn't encounter any problem of this config, I have tested on my own server before I posted it out, and I have checked it again after you opened this issue, it works. I suppose it may be caused by your free domain name, and besides, Caddy won't store any certification directly in the configuration folder or anywhere else, the only way you can test whether the certification has been issued is, open the log and check it. But I don't have any ideas why your log folder doesn't generate any logs, maybe you can use `systemctl status naiveproxy` command to check the logs from docker output, I guess something wrong with Caddy certification issuers' policy.

**Comment by Pacio** [comment] 2022-09-25 16:08
> 
Thanks for the reply, I will try again by changing a paid domain name

**Comment by Pacio** [comment] 2022-09-25 16:24
> > I wonder if it's because I used a free ml domain name because I didn't find any certificate files in the folder
> 
> Sorry but, I didn't encounter any problem of this config, I have tested on my own server before I posted it out, and I have checked it again after you opened this issue, it works. I suppose it may be caused by your free domain name, and besides, Caddy won't store any certification directly in the configuration folder or anywhere else, the only way you can test whether the certification has been issued is, open the log and check it. But I don't have any ideas why your log folder doesn't generate any logs, maybe you can use `systemctl status naiveproxy` command to check the logs from docker output, I guess something wrong with Caddy certification issuers' policy.

systemctl status naiveproxy
* naiveproxy.service - naiveproxy
     Loaded: loaded (/etc/systemd/system/naiveproxy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-09-25 12:21:12 EDT; 14s ago
   Main PID: 5210 (code=exited, status=125)
        CPU: 220ms

Sep 25 12:21:12 debian systemd[1]: naiveproxy.service: Scheduled restart job, restart counter is at 5.
Sep 25 12:21:12 debian systemd[1]: Stopped naiveproxy.
Sep 25 12:21:12 debian systemd[1]: naiveproxy.service: Start request repeated too quickly.
Sep 25 12:21:12 debian systemd[1]: naiveproxy.service: Failed with result 'exit-code'.
Sep 25 12:21:12 debian systemd[1]: Failed to start naiveproxy.


i can't find any useful information

**Comment by bolucat** [comment] 2022-09-25 23:54
Nope, `naiveproxy.service: Start request repeated too quickly.` is useful information, it indicates your config is wrong to Caddy, you can debug with following steps:
- Directly download Caddy binary file : `wget -O /etc/naiveproxy/caddy https://github.com/bolucat/peace/releases/download/v2.6.1/caddy-linux-amd64 && chmod +x /etc/naiveproxy/caddy` (If your architecture is arm64, replace `caddy-linux-amd64` with `caddy-linux-arm64`)
- Validate the config : `/etc/naiveproxy/caddy validate /etc/naiveproxy/Caddyfile` If the output contains `Valid configuration`, it's OK, go ahead, else, post the output here
- Start Caddy : `/etc/naiveproxy/caddy run --config /etc/naiveproxy/Caddyfile` It may exit because of the same reason why in docker your service exit, post the log here

**Comment by Pacio** [comment] 2022-09-26 00:28
> Nope, `naiveproxy.service: Start request repeated too quickly.` is useful information, it indicates your config is wrong to Caddy, you can debug with following steps:
> 
> * Directly download Caddy binary file : `wget -O /etc/naiveproxy/caddy https://github.com/bolucat/peace/releases/download/v2.6.1/caddy-linux-amd64 && chmod +x /etc/naiveproxy/caddy` (If your architecture is arm64, replace `caddy-linux-amd64` with `caddy-linux-arm64`)
> * Validate the config : `/etc/naiveproxy/caddy validate /etc/naiveproxy/Caddyfile` If the output contains `Valid configuration`, it's OK, go ahead, else, post the output here
> * Start Caddy : `/etc/naiveproxy/caddy run --config /etc/naiveproxy/Caddyfile` It may exit because of the same reason why in docker your service exit, post the log here

yeah, the service is running well after changing the domain name and adjusted the caddyfile parameters

**Comment by bolucat** [comment] 2022-09-26 00:38
> 

Well done, Caddy uses `ZeroSSL` and `Let's Encrypt` to issue the certification, it may because of their limitation of free domain name, I will close this issue and have a nice day ☕

**Closed as completed by bolucat** 2022-09-26 00:38 UTC
